version: "3"

services:
    db:
        hostname: db
        image: postgres:15
        container_name: fjob-db-dev
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${PG_NAME}
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASSWORD}
        ports:
            - "5432:5432"
        env_file:
            -  .env
    web:
        hostname: web
        build:
            context: .
            dockerfile: ./config/django/Dockerfile
        container_name: fjob-web-dev
        command: gunicorn fjob.wsgi --bind 0.0.0.0:8001
        volumes:
            - ./fjob:/app
        ports:
            - "8001:8001"
        depends_on:
            - db
            - redis
            - celery
        environment:
            - SECRET_KEY=${SECRET_KEY}
        env_file:
            - .env

    nginx:
        build:
            context: .
            dockerfile: ./config/nginx/Dockerfile
        ports:
            - "80:80"
        depends_on:
            - web
        volumes:
            - ./fjob:/app/

    redis:
        image: redis:latest
        container_name: fjob-redis-dev
        ports:
            - "6379:6379"

    celery:
        build:
            context: .
            dockerfile: ./config/django/Dockerfile
        container_name: fjob-celery-dev
        command: celery -A fjob.celery worker -l info
        volumes:
            - ./fjob:/app/
        depends_on:
            - db
            - redis
        environment:
            - SECRET_KEY=${SECRET_KEY}
        env_file:
            - .env

    celery_beat:
        build:
            context: .
            dockerfile: ./config/django/Dockerfile
        container_name: fjob-celery-beat-dev
        command: celery -A fjob.celery beat -l info
        volumes:
            - ./fjob:/app/
        depends_on:
            - db
            - redis
        environment:
            - SECRET_KEY=${SECRET_KEY}
        env_file:
            - .env