# Generated by Django 4.2.5 on 2023-09-27 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0002_rename_salary_salaries"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offers",
            options={
                "ordering": ("-date_scraped",),
                "verbose_name": "Offer",
                "verbose_name_plural": "Offers",
            },
        ),
        migrations.AlterModelOptions(
            name="salaries",
            options={
                "ordering": ("-salary_from",),
                "verbose_name": "Salary",
                "verbose_name_plural": "Salaries",
            },
        ),
    ]
