# Generated by Django 4.2.5 on 2023-09-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpackage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User Package",
                "verbose_name_plural": "User Packages",
            },
        ),
        migrations.AddField(
            model_name="userpackage",
            name="stripe_checkout_id",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
