# Generated by Django 4.2.5 on 2023-09-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_alter_userpackage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpackage",
            name="custom_id",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
