# Generated by Django 4.2.5 on 2023-10-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_userpackage_custom_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="free_users",
        ),
        migrations.AddField(
            model_name="userpackage",
            name="free_uses",
            field=models.IntegerField(default=5),
        ),
    ]
