# Generated by Django 4.2.5 on 2023-10-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("website", models.CharField(max_length=100)),
                ("is_parsed", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Page Content",
                "verbose_name_plural": "Page Contents",
                "ordering": ["-date_created"],
            },
        ),
    ]
