# Generated by Django 4.2.5 on 2023-10-18 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        choices=[("Poland", "Poland"), ("Germany", "Germany")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("min_salary", models.IntegerField(blank=True, null=True)),
                ("max_salary", models.IntegerField(blank=True, null=True)),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Intern", "Intern"),
                            ("Junior", "Junior"),
                            ("Mid", "Mid"),
                            ("Senior", "Senior"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-id"],
            },
        ),
    ]
